### ISSUE TITLE
Erro quando inicia sem banco

### ISSUE THREAD

**Issue by michaelake** [Rafagd/Tomiko#7]
`INFO:root:Version changed, migrating data.
Traceback (most recent call last):
  File "run.py", line 16, in <module>
    config.migrate()
  File "/home/pi/Documents/tomiko/src/config.py", line 47, in migrate
    globals()['migrate_{}_{}'.format(i, i + 1)](self)
KeyError: 'migrate_0_1'
`

**Comment by Rafagd** [comment]
Resolvido em 880bfc1f53bd71deb5c05d509bba40f9b1dd9815.
